language: php

php:
    - 5.6
    - 7.0
    - 7.1
    - hhvm

before_script:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - composer install --no-interaction

script:
    - vendor/bin/phpunit
